### ISSUE TITLE
Undefined reference to fread_s

### ISSUE THREAD

**Issue by StandingPadAnimations** [Ryan-rsm-McKenzie/binary_io#2]
When compiling with MSYS2, this error will pop up during the linking phase:
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
Lib/libbinary_io.a(binary_io.cpp.obj):binary_io.cpp:(.text+0x1a5): undefined reference to `fread_s
```
From my minimal research, fread_s isn't part of the C++ standard, so it seems to be a portability issue

**Comment by StandingPadAnimations** [comment]
My version of g++ is `g++.exe (Rev2, Built by MSYS2 project) 11.2.0`

**Comment by Ryan-rsm-McKenzie** [comment]
MinGW isn't supported

**Comment by StandingPadAnimations** [comment]
Oh, is there some limitations with supporting MinGW? As far as I know it's just GCC on Windows

**Comment by StandingPadAnimations** [comment]
I've added MinGW support in a pull request so I'll close this
